# Generated by Django 5.0.6 on 2024-07-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sponsor_student_studentsponsor_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='organization',
            field=models.CharField(blank=True, default='null', max_length=123, null=True),
        ),
    ]
