# Generated by Django 5.0.6 on 2024-07-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_sponsor_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='organization',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='person_type',
            field=models.CharField(choices=[('yuridik_shaxs', 'yuridik shaxs'), ('jismoniy_shaxs', 'Jismoniy shaxs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('moderation', 'Moderatsiyada'), ('approved', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='contract_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('bakalavr', 'Bakalavr'), ('master', 'Magistr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.university'),
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.sponsor'),
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.student'),
        ),
    ]
