# Generated by Django 5.0.6 on 2024-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_sponsor_amount_alter_sponsor_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='person_type',
            field=models.CharField(choices=[('legal_entity', 'yuridik shaxs'), ('simple_person', 'Jismoniy shaxs')], max_length=20),
        ),
    ]
