# Generated by Django 5.0.6 on 2024-07-04 13:44

import apps.common.regx
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_sponsor_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[apps.common.regx.validate_uzbekistan_phone_number]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[apps.common.regx.validate_uzbekistan_phone_number]),
        ),
    ]
