# Generated by Django 5.0.6 on 2024-07-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_sponsor_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='payment_type',
            field=models.CharField(choices=[('money_transfers', "pul o'tkazmalari"), ('cash', 'naqt pul orqali')], default='money_transfers', max_length=20),
        ),
    ]
