# Generated by Django 5.0.4 on 2024-07-05 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_studentsponsor_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_sponsors', to='common.sponsor'),
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_sponsors', to='common.student'),
        ),
    ]
